### ISSUE TITLE
is the addon dead?

### ISSUE THREAD

**Issue by Parakovsky** [vincentsimard/dmitlichess#36]
seems not to work and the previous issues on a github indicate that i am not the only one

**Comment by vincentsimard** [comment]
Please provide additional information. "seems not to work" is vague. What browser are you using? OS? Are you able to install the extension? Are you using it while playing or watching lichess TV.

The add-on is not dead. I just have limited time to update it. There were always problems updating the Firefox version due to the size of the package.

Feel free to submit pull requests or bug reports and I'll have a look at them.

Cheers!
